function Comp = addComponents2Panel_View(hPanel)

Comp.hAxis.Image = axes('Parent',                   hPanel, ...
                            'color',        'none',...
                            'xcolor', 'w',...
                            'ycolor', 'w', ...
                            'gridcolor',   'w',...
                            'Units',                    'normalized', ...
                            'HandleVisibility',     'callback', ...
                            'Position',                 [0.05 0.025 0.9 0.9]);

Comp.hAxis.Image.XAxisLocation='top';
hold(Comp.hAxis.Image, 'on') 